# Generated by Django 3.1.4 on 2020-12-03 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_auto_20201203_0945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='comprador',
            field=models.CharField(max_length=79),
        ),
    ]
