# Generated by Django 3.1.4 on 2020-12-03 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
        ('ventas', '0003_auto_20201203_0947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalle',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='productos.producto', verbose_name='Producto'),
        ),
    ]
